# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11x8UCh-V4HZqmpVEHccPaKtNjij1yorO
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("merged_county_data_for_python.csv")

cols = ["income", "population", "total_sales_dollars", "dollars_per_capita"]
numeric_df = df[cols]

corr = numeric_df.corr()
print(corr)

fig, ax = plt.subplots(figsize=(6, 5))

im = ax.imshow(corr, cmap="coolwarm", vmin=-1, vmax=1)
ax.set_xticks(range(len(cols)))
ax.set_yticks(range(len(cols)))
ax.set_xticklabels(cols, rotation=45, ha="right")
ax.set_yticklabels(cols)

cbar = fig.colorbar(im, ax=ax)
cbar.set_label("Correlation")

for i in range(len(cols)):
    for j in range(len(cols)):
        text = ax.text(j, i, f"{corr.iloc[i, j]:.2f}", ha="center", va="center")

plt.title("Correlation Matrix")
plt.tight_layout()
plt.savefig("correlation_matrix.png", dpi=300)
plt.show()